steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops4','.']
- name: 'docker'
  args: ['push','gcr.io/$PROJECT_ID/gcpdevops4']

- name: "gcr.io/cloud-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops4
  - --location=us-central1-c
  - --cluster=gcpdevops1
  - --namespace=gcpdevops-prod
