apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pyapp
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pyapp
    spec:
      containers:
      - image: gcr.io/project-gcp-384311/gcpdevops1
        name: gcpdevops1
        resources: {}
status: {}
